image: elixir:1.6.0-alpine
cache:
  key: flume
  paths:
    - deps

services:
  - redis:alpine

stages:
  - test

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get --only test

test:
  stage: test
  variables:
    FLUME_REDIS_HOST: localhost
    FLUME_REDIS_PORT: 6379
  script:
    - mix test
  tags:
    - staging
    - kubernetes
    - small
